import crypto from 'crypto';

// In-memory challenge store (expired after 3 minutes)
const challengeStore = new Map<string, { challenge: string; expiresAt: number; userId?: string }>();

// Cleanup expired challenges periodically
if (typeof setInterval !== 'undefined') {
  setInterval(() => {
    const now = Date.now();
    for (const [key, val] of challengeStore.entries()) {
      if (val.expiresAt < now) {
        challengeStore.delete(key);
      }
    }
  }, 60 * 1000);
}

/**
 * Generate a cryptographically secure random challenge for WebAuthn
 */
export function generateWebAuthnChallenge(userId?: string): string {
  const challenge = crypto.randomBytes(32).toString('base64url');
  const key = challenge;
  challengeStore.set(key, {
    challenge,
    userId,
    expiresAt: Date.now() + 3 * 60 * 1000, // 3 menit
  });
  return challenge;
}

/**
 * Verify that a challenge was legitimately generated by the server and not expired
 */
export function verifyWebAuthnChallenge(challenge: string): boolean {
  const record = challengeStore.get(challenge);
  if (!record) return false;
  if (record.expiresAt < Date.now()) {
    challengeStore.delete(challenge);
    return false;
  }
  challengeStore.delete(challenge); // One-time use
  return true;
}

/**
 * Helper to encode buffer to Base64URL
 */
export function bufferToBase64URL(buffer: ArrayBuffer | Uint8Array): string {
  const bytes = new Uint8Array(buffer);
  let str = '';
  for (let i = 0; i < bytes.byteLength; i++) {
    str += String.fromCharCode(bytes[i]);
  }
  return Buffer.from(str, 'binary').toString('base64url');
}

/**
 * Helper to decode Base64URL to Buffer
 */
export function base64URLToBuffer(base64url: string): Buffer {
  return Buffer.from(base64url, 'base64url');
}
